version: '2'

services:
    nginx:
        image: nginx:latest
        ports:
        - 8080:80
        volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./logs/nginx-error.log:/var/log/nginx/error.log
        - ./logs/nginx-access.log:/var/log/nginx/access.log
        volumes_from:
          - phpfpm
    phpfpm:
        build: ./php/
        ports:
        - 9000:9000
        volumes:
        - ./web/public:/usr/share/nginx/html
    mysql:
        build: ./mysql/
        environment:
          MYSQL_ROOT_PASSWORD: admin
        volumes:
        - ./data/db/mysql:/var/lib/mysql/
        ports:
        - 8989:3306